apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capsule-proxy
  namespace: flux-system
spec:
  dependsOn:
    - name: capsule
  targetNamespace: capsule-system
  serviceAccountName: helm-controller
  install:
    createNamespace: true
  releaseName: capsule-proxy
  interval: 5m
  chart:
    spec:
      chart: capsule-proxy
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 1m
  values:
    image:
      tag: v0.4.6

